language: node_js

node_js:
  - "8"

before_install:
  - npm install -g npm@latest

cache:
  directories:
    - "node_modules"

before_install :
  - echo "starting installation of dependencies for node.js application"

install:
  - npm install http

after_install :
  - echo "Finishing installation process successfully !"


before_script :
  - echo "Running execution script !!!"

script :
  - node app.js

after_script :
  - echo "Running execution script successfully !!!"
    
before_deploy :
  - echo "Starting deployment of node.js application on to azure provider"

deploy :
  - provider : azure_web_apps
  - username : gslazure-travis-node-user
  - password : gslazure-travis-node-pwd
  - site : https://gslazure-travis-node2.azurewebsites.net
  - verbose : true
  - on:
    all_branches: true

after_deploy :
  - echo "Finishing deployment on to azure provider successfully !"