dist: trusty
sudo: required


before_install:
  - npm install -g npm@latest

cache:
  directories:
    - "node_modules"

before_install :
  - echo "starting installation of dependencies for node.js application"

addons:
  sonarcloud:
    organization: sonarcube-org
    token: f478686cecf461a6ff67cd69f5c552de3c60eda3 

install:
  - npm install http

before_script :
  - echo "Running execution script !!!"

script :
  - sonar-scanner

after_script :
  - echo "Running execution script successfully !!!"
    
before_deploy :
  - echo "Starting deployment of node.js application on to azure provider"

deploy:
  provider: azure_web_apps
  verbose : true
  on:
    all_branches: true

after_deploy :
  - echo "Finishing deployment on to azure provider successfully !"